version: '3.8'

services:
  backend:
    container_name: fastapi
    build: ./app
    environment:
      SQLALCHEMY_DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}"
      WEB_USERNAME: ${WEB_USERNAME}
      WEB_PASSWORD: ${WEB_PASSWORD}
    volumes:
      - ./app:/app
    ports:
      - "${WEB_PORT}:8000"
    depends_on:
      - db
    networks:
      - app-network
      - proxy 


  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
  proxy:
    name: "reverse-proxy"
    external: true

volumes:
  postgres_data:
